service: serverless-express

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: false
    packager: 'npm'

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev

functions:
  api:
    handler: src/index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
